# Generated by Django 3.2.7 on 2022-01-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('content', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': '新闻表',
                'verbose_name_plural': '新闻表',
                'db_table': 'news',
                'ordering': ['name'],
            },
        ),
    ]
