# Generated by Django 3.2.7 on 2021-11-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='license_image',
            field=models.FileField(null=True, upload_to='customer', verbose_name='营业执照图片'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registration_capital',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='注册资金'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remark',
            field=models.TextField(max_length=1024, null=True, verbose_name='备注'),
        ),
    ]
