# Generated by Django 3.2.7 on 2021-11-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20211110_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=32, null=True, verbose_name='所在城市'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_abbreviation_name',
            field=models.CharField(max_length=64, null=True, verbose_name='公司简称'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_address',
            field=models.CharField(max_length=256, null=True, verbose_name='公司地址'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(max_length=32, null=True, verbose_name='联系人姓名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_phone',
            field=models.CharField(max_length=64, null=True, verbose_name='联系人手机号码'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_tel',
            field=models.CharField(max_length=128, null=True, verbose_name='联系人电话'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(max_length=64, null=True, verbose_name='所在行业'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='license_no',
            field=models.CharField(max_length=32, null=True, verbose_name='营业执照号码'),
        ),
    ]
