# Generated by Django 3.2.7 on 2021-11-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20211110_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='registration_date',
            field=models.DateTimeField(verbose_name='注册日期'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registration_effect_end',
            field=models.DateTimeField(verbose_name='有效期结束日期'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registration_effect_start',
            field=models.DateTimeField(verbose_name='有效期开始日期'),
        ),
    ]
