# Generated by Django 3.2.7 on 2021-10-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=16, unique=True)),
                ('station_name', models.CharField(max_length=32)),
                ('station_address', models.CharField(max_length=100)),
                ('facility_code', models.CharField(max_length=16)),
                ('employees', models.CharField(max_length=16)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField()),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '场站类',
                'verbose_name_plural': '场站类',
                'db_table': 'station',
                'ordering': ['-station_code'],
            },
        ),
    ]
