# Generated by Django 3.2.7 on 2022-02-22 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='国家两字码')),
                ('chn_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='国家中文全称')),
                ('eng_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='国家英文全称')),
                ('continent', models.CharField(blank=True, max_length=64, null=True, verbose_name='所在洲')),
                ('tel_zone', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话区号')),
                ('time_difference', models.CharField(blank=True, max_length=32, null=True, verbose_name='时差')),
                ('national_flag_img', models.CharField(blank=True, max_length=128, null=True, verbose_name='国旗图片')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('is_delete', models.BooleanField(default=False, verbose_name='软删除标志')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建记录日期')),
                ('create_by', models.CharField(max_length=32, verbose_name='创建人')),
                ('update_datetime', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新记录日期')),
                ('update_by', models.CharField(max_length=32, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '全球国家两字码表',
                'verbose_name_plural': '全球国家两字码表',
                'db_table': 'country',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='城市三字码')),
                ('country_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universalCode.country', to_field='code', verbose_name='国家两字码')),
                ('eng_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='城市英文全称')),
                ('chn_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='城市中文全称')),
                ('time_zone', models.CharField(blank=True, max_length=32, null=True, verbose_name='时区')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('is_delete', models.BooleanField(default=False, verbose_name='软删除标志')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建记录日期')),
                ('create_by', models.CharField(max_length=32, verbose_name='创建人')),
                ('update_datetime', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新记录日期')),
                ('update_by', models.CharField(max_length=32, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '全球城市三字码表',
                'verbose_name_plural': '全球城市三字码表',
                'db_table': 'city',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=16, unique=True, verbose_name='IATA机场代码')),
                ('icao_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='ICAO机场代码')),
                ('chn_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='机场中文名称')),
                ('eng_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='机场英文名称')),
                ('country_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universalCode.country', to_field='code', verbose_name='所在国家')),
                ('city_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='城市三字码')),
                ('city_chn_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='城市中文名称')),
                ('city_eng_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='城市英文名称')),
                ('elevation', models.CharField(blank=True, max_length=64, null=True, verbose_name='海拨高度')),
                ('longitude', models.CharField(blank=True, max_length=64, null=True, verbose_name='经度')),
                ('latitude', models.CharField(blank=True, max_length=64, null=True, verbose_name='纬度')),
                ('time_zone', models.CharField(blank=True, max_length=64, null=True, verbose_name='时区')),
                ('utc', models.CharField(blank=True, max_length=16, null=True, verbose_name='UTC时差')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('is_delete', models.BooleanField(default=False, verbose_name='软删除标志')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建记录日期')),
                ('create_by', models.CharField(max_length=32, verbose_name='创建人')),
                ('update_datetime', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新记录日期')),
                ('update_by', models.CharField(max_length=32, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '全球机场三字码表',
                'verbose_name_plural': '全球机场三字码表',
                'db_table': 'airport',
                'ordering': ['iata_code'],
            },
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='IATA机场代码')),
                ('icao_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='ICAO机场代码')),
                ('accounting_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='ICAO机场代码')),
                ('airline_prefix_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='ICAO机场代码')),
                ('chn_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='机场中文名称')),
                ('eng_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='机场英文名称')),
                ('call_sign', models.CharField(blank=True, max_length=64, null=True, verbose_name='机场英文名称')),
                ('country_code', models.ForeignKey(blank=True, max_length=16, null=True, on_delete=django.db.models.deletion.CASCADE, to='universalCode.country', to_field='code', verbose_name='所在国家')),
                ('city_code', models.ForeignKey(blank=True, max_length=16, null=True, on_delete=django.db.models.deletion.CASCADE, to='universalCode.city', to_field='code', verbose_name='城市三字码')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('is_delete', models.BooleanField(default=False, verbose_name='软删除标志')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建记录日期')),
                ('create_by', models.CharField(max_length=32, verbose_name='创建人')),
                ('update_datetime', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新记录日期')),
                ('update_by', models.CharField(max_length=32, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '全球航空公司二字码表',
                'verbose_name_plural': '全球航空公司二字码表',
                'db_table': 'airline',
                'ordering': ['iata_code'],
            },
        ),
    ]
