# Generated by Django 4.0.2 on 2022-03-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universalCode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='capital',
        ),
        migrations.AddField(
            model_name='country',
            name='capital_chn_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='首都中文名称'),
        ),
        migrations.AddField(
            model_name='country',
            name='capital_eng_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='首都英文名称'),
        ),
    ]
