# Generated by Django 3.2.7 on 2022-02-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universalCode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='phone_zone',
            new_name='phone_code',
        ),
    ]
