# Generated by Django 3.2.7 on 2022-02-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universalCode', '0002_rename_phone_zone_country_phone_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='continent_id',
            new_name='continent',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='country_id',
            new_name='country',
        ),
    ]
