# Generated by Django 4.0.2 on 2022-02-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universalCode', '0002_alter_airline_chn_name_alter_airline_eng_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='iata_code',
            field=models.CharField(max_length=16, verbose_name='IATA机场代码'),
        ),
    ]
