# Generated by Django 4.0.2 on 2022-02-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universalCode', '0003_alter_airline_iata_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='iata_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='IATA机场代码'),
        ),
    ]
