# Generated by Django 3.2.7 on 2022-02-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universalCode', '0003_auto_20220226_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso3_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='国家三字码'),
        ),
    ]
