# Generated by Django 3.2.7 on 2022-02-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universalCode', '0004_alter_country_iso3_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='iso2_code',
            field=models.CharField(max_length=16, verbose_name='省两字码(可重复)'),
        ),
    ]
