# Generated by Django 3.2.7 on 2022-02-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universalCode', '0005_alter_state_iso2_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='iso3_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='城市三字码(先设置为空，以后再补)'),
        ),
    ]
