# Generated by Django 3.2.7 on 2022-02-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universalCode', '0006_alter_city_iso3_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='city_ios3_code',
            new_name='city_iso3_code',
        ),
    ]
