# Generated by Django 3.2.7 on 2021-10-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['station_code'], 'verbose_name': '场站类', 'verbose_name_plural': '场站类'},
        ),
    ]
