# Generated by Django 4.0.2 on 2022-03-23 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='软删除标志')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建记录日期')),
                ('create_by', models.CharField(max_length=32, verbose_name='创建人')),
                ('update_datetime', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新记录日期')),
                ('update_by', models.CharField(max_length=32, verbose_name='更新人')),
                ('account', models.CharField(max_length=16, unique=True, verbose_name='账号')),
                ('abbreviation_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='简称')),
                ('full_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='全称')),
                ('architecture', models.CharField(blank=True, max_length=64, null=True, verbose_name='体系结构（总部/分公司/子公司）')),
                ('unified_social_credit_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='统一社会信用代码')),
                ('business_licence_image', models.ImageField(default='default.jpg', upload_to='businessLicenceImage', verbose_name='照业执照图片')),
                ('registered_capital', models.CharField(blank=True, max_length=32, null=True, verbose_name='注册资本')),
                ('registered_address', models.CharField(blank=True, max_length=32, null=True, verbose_name='注册地址')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='成立日期')),
                ('effective_start_date', models.DateField(blank=True, null=True, verbose_name='营业期限(起)')),
                ('effective_end_date', models.DateField(blank=True, null=True, verbose_name='营业期限(止)')),
                ('office_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='办公地址')),
                ('business_scope', models.TextField(blank=True, max_length=128, null=True, verbose_name='经营范围')),
                ('country', models.CharField(blank=True, max_length=64, null=True, verbose_name='所在国家')),
                ('province', models.CharField(blank=True, max_length=64, null=True, verbose_name='所在省/洲')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='所在城市')),
                ('district', models.CharField(blank=True, max_length=64, null=True, verbose_name='所在区/县')),
                ('industry', models.CharField(blank=True, max_length=32, null=True, verbose_name='所在行业')),
                ('website', models.CharField(blank=True, max_length=64, null=True, verbose_name='企业网站')),
                ('legal_person_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='法人姓名')),
                ('legal_person_phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='法人电话')),
                ('legal_person_email', models.CharField(blank=True, max_length=64, null=True, verbose_name='法人邮箱')),
                ('banking_account_info', models.TextField(blank=True, max_length=256, null=True, verbose_name='银行对公账户信息')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('is_available', models.BooleanField(default=False, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '供应商表',
                'verbose_name_plural': '供应商表',
                'db_table': 'supplier',
                'ordering': ['account'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=32, verbose_name='部门名称')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='职位')),
                ('chn_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='中文名')),
                ('eng_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='英文名')),
                ('tel', models.CharField(blank=True, max_length=128, null=True, verbose_name='电话')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='手机')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='邮箱')),
                ('wechat', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信号')),
                ('qq', models.CharField(blank=True, max_length=64, null=True, verbose_name='QQ号')),
                ('social_account', models.TextField(blank=True, max_length=256, null=True, verbose_name='其他社交账号')),
                ('remark', models.TextField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='supplier.supplier', verbose_name='供应商id(外键)')),
            ],
            options={
                'verbose_name': '供应商联系人表',
                'verbose_name_plural': '供应商联系人表',
                'db_table': 'supplier_contact',
                'ordering': ['department'],
            },
        ),
    ]
