# Generated by Django 3.2.7 on 2022-04-09 19:19

from django.db import migrations, models
import utils.system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'get_latest_by': 'account', 'ordering': ['id'], 'verbose_name': '供应商表', 'verbose_name_plural': '供应商表'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='business_licence_image',
            field=models.FileField(blank=True, default='default.jpg', null=True, storage=utils.system.storage.ImageStorage(), upload_to='supplierBusinessLicenceImage', verbose_name='照业执照图片'),
        ),
    ]
