# Generated by Django 3.2.7 on 2022-04-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20220409_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='business_licence_image',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='supplierBusinessLicenceImage', verbose_name='照业执照图片'),
        ),
    ]
