# Generated by Django 4.0.2 on 2022-04-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_supplier_business_licence_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='business_scope',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='经营范围'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='office_address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='办公地址'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='registered_address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='注册地址'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.IntegerField(choices=[(0, '新建'), (1, '启用'), (2, '禁用')], verbose_name='状态'),
        ),
    ]
