# Generated by Django 4.0.2 on 2022-04-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_remove_supplier_industry_supplier_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='service_type',
        ),
        migrations.AddField(
            model_name='supplier',
            name='enterprise_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='企业类型'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.IntegerField(choices=[(0, '新建'), (1, '启用'), (2, '禁用')], verbose_name='使用状态'),
        ),
    ]
