# Generated by Django 3.2.7 on 2021-10-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_title', models.CharField(blank=True, max_length=20, null=True)),
                ('goods_price', models.CharField(blank=True, max_length=20, null=True)),
                ('goods_image', models.FileField(blank=True, null=True, upload_to='goods', verbose_name='商品图片')),
                ('goods_kind', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': '商品类',
                'verbose_name_plural': '商品类',
                'db_table': 'goods',
                'ordering': ['goods_title'],
            },
        ),
    ]
