# Generated by Django 3.2.7 on 2022-02-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=16, unique=True, verbose_name='IATA机场代码')),
                ('icao_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='ICAO机场代码')),
                ('airport_chn_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='机场中文名称')),
                ('airport_eng_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='机场英文名称')),
                ('country_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='国家/地区代码')),
                ('country_chn_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='国家/地区中文名称')),
                ('country_eng_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='国家/地区英文名称')),
                ('city_chn_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='城市中文名称')),
                ('city_eng_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='城市英文名称')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=False, verbose_name='软删除标志')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建记录日期')),
                ('create_by', models.CharField(max_length=32, verbose_name='创建人')),
                ('update_datetime', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新记录日期')),
                ('update_by', models.CharField(max_length=32, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '全球机场三字码表',
                'verbose_name_plural': '全球机场三字码表',
                'db_table': 'airport',
                'ordering': ['iata_code'],
            },
        ),
    ]
