# Generated by Django 4.0.2 on 2022-02-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='elevation',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='海拨高度'),
        ),
        migrations.AddField(
            model_name='airport',
            name='latitude',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='airport',
            name='longitude',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='airport',
            name='time_zone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='时区'),
        ),
        migrations.AddField(
            model_name='airport',
            name='utc',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='UTC时差'),
        ),
    ]
