# Generated by Django 3.2.7 on 2022-03-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='课程名称')),
                ('sex', models.BooleanField(default=False, verbose_name='性别')),
            ],
            options={
                'verbose_name': '老师表',
                'verbose_name_plural': '老师表',
                'db_table': 'sch_teacher',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='学校名称')),
                ('age', models.SmallIntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(default=False, verbose_name='性别')),
            ],
            options={
                'verbose_name': '学生表',
                'verbose_name_plural': '学生表',
                'db_table': 'sch_student',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='老师姓名')),
                ('teacher', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course', to='school.teacher', verbose_name='老师外键')),
            ],
            options={
                'verbose_name': '课程表',
                'verbose_name_plural': '课程表',
                'db_table': 'sch_course',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_created=True)),
                ('score', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='成绩')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='c_achievement', to='school.course', verbose_name='老师外键')),
                ('student', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='s_achievement', to='school.student')),
            ],
            options={
                'verbose_name': '成绩表',
                'verbose_name_plural': '成绩表',
                'db_table': 'sch_achievement',
                'ordering': ['score'],
            },
        ),
    ]
