# Generated by Django 3.2.7 on 2021-09-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': '图书类',
                'verbose_name_plural': '图书类',
                'db_table': 'books',
                'ordering': ['-name'],
            },
        ),
    ]
