# Generated by Django 3.2.7 on 2022-03-31 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('is_delete', models.BooleanField(default=0, verbose_name='删除标志')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name_plural': '品牌表',
                'db_table': 'demo_brand',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('is_delete', models.BooleanField(default=0, verbose_name='删除标志')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name_plural': '赞助商表',
                'db_table': 'demo_sponsor',
            },
        ),
        migrations.CreateModel(
            name='SponsorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('is_delete', models.BooleanField(default=1)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('sponsor', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detail', to='cars.sponsor')),
            ],
            options={
                'verbose_name_plural': '赞助商详情表',
                'db_table': 'demo_sponsor_detail',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('is_delete', models.BooleanField(default=0, verbose_name='删除标志')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='价格')),
                ('brand', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Cars', to='cars.brand', verbose_name='品牌')),
                ('sponsors', models.ManyToManyField(db_constraint=False, related_name='Cars', to='cars.Sponsor', verbose_name='赞助商')),
            ],
            options={
                'verbose_name_plural': '汽车表',
                'db_table': 'demo_car',
            },
        ),
    ]
